splashList = [
'Jangan takut terhadap orang di posisi manapun, rendah ataupun tinggi, entah dia cendekiawan atau orang yang tidak berpengetahuan. Kalau kau hormat kepada semua manusia, kau harus mengasihi semua orang, dan tidak merasa takut kepada siapapun.',
'Jangan biarkan jati diri menyatu dengan pekerjaan Anda. Jika pekerjaan lenyap, maka jati diri Anda tidak akan pernah hilang.',
'Surga dan Bumi itu abadi. Keduanya abadi karena tidak ada bagi dirinya sendiri. Dengan cara yang sama, orang yang benar-benar suci tak hanya hidup bagi dirinya sendiri, karenanya bisa menjadi abadi dan meraih apapun.',
'Manangguak di aia karuah.',
'Menangguk di air keruh.',
'Mencari keuntungan dalam kekacauan.',
'Tiga hal siapa yang melakukannya, maka ia berpotensi mendapatkan murka: tertawa tanpa ada sesuatu yang mengejutkan, tidur tanpa begadang, dan makan tanpa rasa lapar.',
'Jika Amerika Serikat salah, harapan apa yang kita miliki dari dunia beradab pada gilirannya?',
'Tidak ada yang peduli pada nasib buruh, selama mereka mendapatkan kepuasan secara instan.',
'Had Iraq and Libya been nuclear powers, they wouldn’t have been destroyed in the way we have seen recently. If we had had nuclear capability before 1971, we would not have lost half of our country—present-day Bangladesh—after disgraceful defeat.',
'To project ourselves into their final thoughts will require feelings about a special kind of death - the sudden death in fire of the young, elite, unfulfilled, and seemingly unconquerable. As the elite of young men, they felt more surely than most who are young that they were immortal.',
'HIV/AIDS is a personal challenge, a challenge affecting individuals, families and communities.',
'The Pythagoreans thought those who teach for the sake of reward show themselves worse than sculptors, or artists who perform the work sitting. For these, when someone orders wood to make a statue of Hermes, search for wood suited to receive the proper form; while those pretend that they can readily produce the works of virtue from every nature.',
'Forgive us our trespasses, as we forgive those who trespass against us.',
'Ronnie is the best player in the world at the moment, right-handed, left-handed, one-legged, one-armed, whatever you want!',
'But alas, I\'m going to die!',
'I\'m a chap who...clings to life with the fingernails of both hands.',
'One who drinks of love till it overflows his lips,',
'The other night I sat alone in agony,',
'Listening to the hours pass, wracked with sorrow...',
'I have arrived to face the cold border of nihility.',
'The things which for the most part offer themselves in life, and which, to judge from their actions, men regard as the highest good, can be reduced to these three headings: riches, honour, and sensual pleasure. With these three the mind is so distracted that it is quite incapable of thinking of any other good.',
'AHINDA as a socio-political philosophy can be used as a tool to prevent youths from backward classes and Dalit communities from joining the Hindutva brigade.',
'Wikipedia would have never gotten off the ground without the support of Wales and Bomis.',
'Harvey was not content merely to gather knowledge; he digested and arranged it under the guidance of the faculties which compare and reason.',
'¡Qué rico es ser boricua!',
'Ye monsters of the bubbling deep,<br>Your Maker\'s praises spout;<br>Up from the sands ye codlings peep,<br>And wag your tails about.',
'The silver medal for me was a sign that I would achieve a lot in athletics if I gave it time and work hard.',
'Don\'t know what I\'d do without ya, Ma.',
'So when she wants to take you, she takes you...',
'If controversy means the stimulation of thought and ideas, so much the better.',
'But we, the great, the valiant, and the wise,<br>When once the seal of death has closed our eyes,<br>Lost in the hollow tomb obscure and deep,<br>Slumber, to wake no more, one long unbroken sleep!',
'I\'ll see you next time!',
'When we see a film, half of what we see is what we bring to it.',
'Just because my butt is so humble.',
'A ring around the finger does not cause a nerve block to the genitals.',
'Masuk tak genap, keluar tak ganjil.',
'Makin murah, makin ditawar.',
'Hidung dicium pipi digigit.',
'There must be no hesitation to assume control of the means of production where that is essential in the public interest.',
'Trapped dreams must die.',
'Yew-Kwang Ng is ‘one of the leading economic theorists of his generation’, with a ‘remarkable research record’, who has made ‘major contributions in theoretical Welfare Economics’.',
'O violet-tressed Sappho chaste,<br>O maid with honeyed smile!<br>I fain would tell what is in my breast,<br>Did shame me not beguile.',
'We are the generation that was created by Museveni’s failures...',
'Thank you, Jīya.',
'To the mass of the nation it is the venerability and continuity of our monarchy that gives it so strong and wide a sentimental appeal.',
'It is very important to have the values, the necessary competences to build social cohesion.',
'I believe that a healthy and inclusive democracy is the ultimate check on radicalization.',
'I haven\'t been giving you the silent treatment. I just haven\'t been talking to you.',
'More fool you.',
'Bolshevism destroys not only private property but also private initiative and the readiness to shoulder responsibility. It has not been able to save millions of human beings from starvation in Russia, the greatest Agrarian State in the world.',
'Do you smell something burning?',
'I\'m waiting for valentines.',
'I was attracted to money. I was attracted to the idea of doing what I wanted to do, which was not being a little Southern girl like little Southern girls were for the last, you know, 300 years, but to instead see what it was like to go all over the world and what it was like to be with different people in different places and to see what their lives were like...',
'Let\'s get this party started!',
'Forth, no Soldiers can be quartered in the House of any Freeman in time of Peace, without his will...',
'Did he have passion?',
'By convention sweet is sweet, bitter is bitter, hot is hot, cold is cold, color is color; but in truth there are only atoms and the void.',
'If global warming extinguishes humanity, according to total utilitarianism, that would be an inconceivably bad disaster.',
'Hakimi sebuah pohon dari buahnya, bukan daunnya.',
'Adat bersendi syarak, syarak bersendi adat.',
'Sedekah adalah memberi sesuatu untuk memenuhi kebutuhan orang lain secara sukarela tanpa kepentingan apapun.',
'Emping terserak, hari hujan.',
'Salah satu beban dari pendidikan ekologi adalah kita hidup di dunia yang penuh dengan luka.',
'Gereja bilang bumi itu datar, tapi saya tahu bumi sebenarnya bulat, karena saya telah melihat bayangan bumi yang jatuh di permukaan bulan, dan saya lebih mempercayai bayangan daripada gereja.',
'Air orang disauk, ranting orang dipatah, adat orang diturut.',
'Mencencang memampas, membunuh membangun.',
'Tapi saya sudah nggak peduli dan EGP kalau dia masih tidak mau mengakuinya.',
'Menangguk di air keruh.',
'Alamat biduk akan karam.',
'Dahulu buah daripada bunga.',
'Men kan nooit weten, hoe een koe een haas vangt.',
'Sebagai abu di atas tanggul.',
'Sayangkan kain, buangkan baju.',
'Tak ada yang terbang terlalu tinggi, jika ia terbang menggunakan sayapnya sendiri.',
'Cut your coat according to your cloth.',
'Orang yang sukses adalah mereka yang memiliki sikap optimis sebesar daya kekuatan kuda dan sikap pesimis sebesar rem darurat.',
'Tidak ada seorang pun yang berbuat zina kecuali Allah cabut cahaya iman dari dirinya.',
'Huli man daw at magaling, naihahabol din.',
'Jangan lupa memberi makan burung merpati.',
'Ambillah pakaian orang yang menanggung orang lain, dan tahanlah dia sebagai sandera ganti orang asing',
'Sambil menyelam minum air.',
'Tidak Presiden, tidak saya, dan tidak menteri-menteri dalam akan mengizinkan senjata untuk digunakan melawan rakyat kami.',
'Baguru kapalang aja bagai bungo kambang tak jadi.',
'Lidah bercabang bagai biawak.',
'Yang hampa biar terbang, yang bernas biar tinggal.',
'Sirih pulang ke gagang, pinang pulang ke tampuk.',
'Jika anda bertanya pada saya untuk menamai tiga masalah paling mengerikan yang dihadapi manusia, aku akan memberi jawaban yang sama dengan yang akan dijawab orang lain: perang nuklir, pemanasan global, dan Windows.',
'Na Driekoningen wordt elke dag de stap van de haan langer.',
'There are two words I hate and despise and don’t want to hear: red carpet and iconic.',
'Civic life requires settings in which people meet as equals, without regard to race, class, or national origins.',
'It is impossible for a Christian to be a relativist.',
'We don\'t have a choice',
'The Spanish Civil War shaped the political consciousness of a whole generation, which overwhelmingly saw it as representing heroic resistance to Fascism.',
'Together, we must advance unafraid into the modern age!',
'The entertainment industry makes this [phantasmagoria of distraction] easier by elevating the person to the level of the commodity. He surrenders to its manipulations while enjoying his alienation from himself and others. The enthronement of the commodity, with its lustre of distraction…is consistent with the split between utopian and cynical elements.',
'The job of a composer is to write whatever a show requires. The range is indeed quite broad, as you know, and in truth, each and every style has a unique set of challenges and rewards.',
'Short on glamour and long on tragedy.',
'One man trapped by destiny, and another bound by duty. They\'re about to discover what they\'re willing to fight, and to die for.',
'Chess is not Mathematics, where ten is always more than one.',
'What on earth am I here for?',
'Kalian memperkenalkan kepada negara kami - melalui kepribadian kalian - ciri-ciri kebudayaan Barat yang menarik yang belum pernah rakyat kami lihat sebelumnya dari orang-orang kulit putih. Maksud saya kesantunan, kebaikan hati, serta ketahanan diri Anda yang patut dihargai.',
'Aku memimpikan lukisanku, lalu aku melukiskan mimpiku.',
'Air orang disauk, ranting orang dipatah, adat orang diturut.',
'Bagai kucing tidur dibantal.',
'Bakar tak berbau.',
'Bagai roda berputar.',
'Cut your coat according to your cloth.',
'Hampa berat menjadi sekam.',
'Ayam ditambat disambar elang.',
'Jinak-jinak merpati, sudah dekat terbanglah dia.',
'Musafir adalah seseorang yang mengadakan perjalanan dengan jarak yang sangat jauh.',
'Salamo aia ilia salamo gagak hitam.',
'Kalau orang bicara Agama, akan bicara benar salah.. Kalau orang bicara hukum, orang akan tanya adil dan curang.. Kalau orang Bicara Politik, akan bicara bersih dan kotor.. Kalau Orang bicara Ekonomi, Akan bicara naik dan turun..<br>Kalau orang bicara Tari, Akan Stabil.. Tidak tinggi rendah.. Itulah Makna tari transformasi dengan komposisi Seimbang.',
'Orang yang memegang kekuasaan cenderung menyalahgunakannya. Orang yang memegang kekuasaan dengan mutlak, pasti akan menyalagunakannya.',
'Pemenuhan kewajiban kita dan rasa puas akan kesenangan pribadi kita adalah dua hal berbeda. Kewajiban punya aturan sendiri, dan bahkan kalau kita berusaha mencampurkan kewajiban dengan kesenangan, keduanya akan memisahkan diri.',
'Bagai meminum air bercacing.',
'Di atas angin.',
'Laziness is the key to beggary.',
'Tuhan, Yang Maha Agung dan Mulia, tidak membiarkan kita memilih tantangan-tantangan baru. Tetapi, Dia berharap kita memilih respon kita terhadap tantangan-tantangan yang sudah ada.',
'Mobulalu',
'Rusak badan karena penyakit, rusak bangsa karena laku.',
'Seluruh militer setia kepada negara, setia pada konstitusi dan menjalankan perintah sesuai dengan undang-undang. Hal ini tidak perlu dipertanyakan.',
'One ending will start one new beginning. Be it a new day, a new season, a new house, a new job, a new relationship, to the things that form the foundation of our thinking, new understanding.',
'Beberapa hal menjadi indah karena tidak bisa dimiliki.',
'Semakin aku memikirkannya, semakin besar aku merasakan bahwa tiada yang lebih berseni dari pada mencintai manusia.',
'Kekuasaan tak terbatas atau absolut/mutlak, merusak orang yang memilikinya.',
'Harum seperti malaikat lalu.',
'Pembebasan seseorang harusnya tidak dilihat sebagai terobosan untuk demokrasi, tetapi demokrasi adalah saat seluruh rakyat menikmati kebebasan.',
'Kebutuhan adalah susah.',
'Delapan tapak bayang-bayang.',
'Belajarlah dari pengorbanan hujan, yang akan jatuh berkali-kali demi terciptanya pelangi.',
'Hangat-hangat tahi ayam.',
'Racun diminum haram tak mabuk.',
'Masalah ekonomi manusia yang sesungguhnya merupakan bagian dari masalah kehidupan manusia yang lebih luas, telah dipisahkan dari keseluruhan dan terlihat seakan-akan masalah yang berdiri sendiri. Lalu lama kelamaan sikap ini berakar kuat bahwa masalah ekonomi telah dianggap sebagai satu-satunya masalah kehidupan. Hal ini menjadikan pengembangannya semakin sulit.',
'Ketika saya membaca tentang bagaimana dana perpustakaan semakin dikurangi, saya hanya dapat berpikir bahwa masyarakat Amerika Serikat telah menemukan cara lain untuk menghancurkan dirinya sendiri.',
'Seperti birah tumbuh di tepi lesung.',
'Air yang dingin juga yang memadami api.',
'Orang bersiselam, awak bertimba.',
'Jawi hitam banyak tingkah.',
'Tidak dirauk menjeriau.',
'Bagai pagar makan tumbuhan.',
'Negara-negara di Eropa punya kurang lebih empat juta orang yang bertugas menjadi tentara. Dua pertiga anggaran negara-negara itu dihabiskan untuk belanja militer.',
'Bagai aur di atas bukit.',
'Seolah-olah ada rencana untuk menekan pergerakan-pergerakan Islam agar kehilangan kepercayaan terhadap demokrasi dan menggunakan jalan kekerasan.',
'Orang berdendang dipentasnya, orang beraja dihatinya.',
'Nafas tak sampai ke hidung.',
'Salah bagi seseorang untuk mengatur banyak orang, seperti halnya salah bagi banyak orang untuk mengatur satu orang.',
'Yang Mulia, orang Yahudi!',
'Menikmati kebahagiaan tanpa memperjuangkannya lebih kurang terpuji dibandingkan dengan menghamburkan kekayaan tanpa ikut mencarinya.',
'Laksana apung-apung dipermainkan ombak.',
'Kebiasaan tak pernah bagus, bahkan kebiasaan melakukan perbuatan baik. Perbuatan baik, setelah menjadi kebiasaan, tak lagi menjadi tindakan bernilai moral tinggi. Kebaikan sejati hanya dicapai lewat usaha.',
'Tak emas bungkal diasah.',
'Kau harus menghargai orang lain, tak peduli semenyebalkan atau sekonyol apa mereka. Kau harus ingat bahwa dalam diri semua orang terdapat semangat yang sama dengan yang hidup dalam diri kita.',
'Bagai pagar makan tumbuhan.',
'Waspadai cemburu karena cemburu itu kunci perceraian. Berdandanlah dan sebaik-baik dandanan adalah celak. Pakailah parfum dan sebaik-baik parfum adalah berwudu dengan sempurna.',
'Aliran pemikiran yang terus-menerus diungkapkan oleh orang lain bisa menghentikan dan melemahkan pemikiran serta inisiatifmu sendiri. Itulah sebabnya pembelajaran terus-menerus memperlemah otakmu. Menghentikan upaya pikiranmu sendiri untuk memberi ruang bagi pemikiran dari buku lain mengingatkanku akan ucapan Shakespeare tentang rekannya yang menjual tanah untuk melihat negara lain.',
'Orang yang hidup lebih membutuhkan kemurahan hati daripada orang yang mati.',
'Dangkal telah keseberangan, dalam telah keajukan.',
'Berbahagialah, mereka yang dapat mengerti penyebab sesuatu.',
'Kau harusnya sudah pikirkan itu sebelumnya.',
'Betapa banyaknya pengetahuan yang diperoleh dari penjelajahan manusia ke bulan.',
'Air tenang menghanyutkan.',
'Datang nampak muko, pai nampak pungguang.',
'Datang tampak muka, pergi tampak punggung.',
'Imajinasi bukan sebuah kekuatan empiris atau tambahan dari kesadaran, ia adalah kesadaran seutuhnya saat menyatakan kebebasannya.',
'Orang cerdik pandai menemukan pikiran baru, orang goblok yang menyebarkannya.',
'Kesalahan terburuk yang pernah dibuat di dunia ini adalah pemisahan pengetahuan politis dari etika.',
'Bagai meminum air bercacing.',
'Uang hanyalah alat pertukaran barang dan jasa yang memang disepakati untuk ‘DIPERDAGANGKAN’<br>Oleh karena itu, ‘PEMBAYARAN’ harus mengembalikan ‘BARANG’ atau ‘JASA’ yang ‘DISEPAKATI SETARA’ dengan nilai uang tersebut.',
'Ajaran orang bijaksana merupakan sumber kehidupan dan menjauhkan orang dari ancaman maut.',
'Seiring bertukar jalan.',
'Pelopor westernisasi dunia Islam – Sir Sayyid Ahmad Khan, Syeh Muhammad Abduh, Qosim Amin, Syeh Ali Abdul Raziq, Dr. Taha Husein, Ziya Gokalp, dan Mustafa Kemal Attaturk. Semua orang ini hanyalah produk akhir sedang-sedang saja dari keadaan mereka dan lebih khususnya akibat dari rasa rendah diri yang terlalu besar yang melanda Timur setelah penyerahan yang memalukan di bawah kaki Imperialis Barat.',
'Cinta adalah hal yang menggilas setiap pengikut gerak cinta. Namun, tanpa gilasan cinta, maka tidaklah kita dapat menikmati keindahan hidup ini.',
'Bagai denai gajah lalu.',
'Mempertahankan fokus adalah kunci sukses. Anda seharusnya memahami bidang kompetensi Anda, keterampilan Anda, dan menghabiskan waktu serta energi Anda di sana.',
'Kita mendaki gunung yang tertinggi, kita membuat gurun mekar. Kita sangat kreatif, kita dapat berjalan di bulan. Tapi begitu saya mendengar bagaimana hutan mengalami kematian, air asin membanjiri mataku.',
'Asal ayam ke lesung, asal itik ke pelimbahan.',
'Dimandikan dengan air segeluk.',
'Melihat wanita yang cakap memegang posisi otoritas dan penting di negara ini sangat membesarkan hati kaum muda, terutama anak perempuan.',
'Penciptaan adalah konsep teologi dan agama mengenai sesuatu yang tidak ada menjadi ada karena kehendak Tuhan.',
'Mereka hanya ingin pulang, mereka ingin selamat!',
'Saya berusaha melakukan kerja sama dengan para pencipta lagu, juga dengan mereka yang tengah naik daun, sehingga kita tak ketinggalan trend.',
'Bahasa-bahasa Barat adalah perwujudan logika, dan logika adalah proses. Jadi jika kita menghaluskan proses lewat penggunaan kata-kata yang semakin meluas, kita bisa menangkapnya secara lebih dekat pada kebenaran.',
'Minta air di gunung, minta angin di lembah.',
'Dunia ini seluruhnya adalah gelap gulita kecuali majelis para ulama.',
'Jalan raya titian batu.',
'Pemahaman akan kehendak Tuhan akan mungkin dengan nalar, dan diperkuat dengan wahyu.',
'Beranak menurut kata bidan.',
'Tidak ada negara yang begitu toleran seperti Indonesia di muka bumi.',
'None thrives for long upon the happiest dream.',
'What is introductory goes for nothing, but it is in order to explain the evidence.',
'For the animals that didn\'t have a dad to put them in a boat, the end of the world already happened.',
'A Romantic Comedy About Letting Go!',
'Oil prices are finally falling.',
'Modern society is too quick to judge people on their appearances. There is not much you can do about it; it is the way they think; it is the way they are. But maybe this could teach them a lesson, or set an example.',
'The flies go up the window,<br>They\'ve nothing else to do,<br>They go up in their hundreds<br>And they come down two by two.',
'A disc jockey (abbreviated D.J., DJ or deejay) is a person who mixes recorded music for an audience; in a club event or rave, this is an audience of dancers.',
'Oh, rolling round the ocean,<br>From a far and foreign land,<br>May suit the common notion<br>That a sailor\'s life is grand.<br>But as for me, I\'d sooner be<br>A roaring here at home<br>About the rolling, roaring life<br>Of them that sails the foam.<br>For the homeward-bounder\'s chorus,<br>Which he roars across the foam,<br>Is all about chucking a sailor\'s life,<br>And settling down at home.<br>Home, home, home,<br>That\'s the song of them that roam,<br>The song of the roaring, rolling sea<br>Is all about rolling home.<br>',
'If anyone assumes that going one\'s own way is the easy way, they are very much in error. There\'s no harder way to go.',
'When I am on stage, the real me comes out.',
'I really didn\'t say everything I said.',
'Everybody wanted to be depressed. But your depression was supposed to be funny, too, and that was what had proved too much for Dolores.',
'Joy, sadness, confidence, anxiety, love, hatred, fear — all of these feelings and thousands more that make up the human “heart” are as useless to the living dead as the organ of the same name. Who knows if this is humanity’s greatest weakness or strength? The debate continues, and probably will forever.',
'Chala chimodzi sichiswa nsabwe',
'One finger does not crush a louse',
'In December 2020, it was announced that HBO was developing a reboot of True Blood.',
'I must strive to reform myself and people of the entire world.',
'I\'m doin\' radio and there\'s a bag in front of me on the console that says \'Butt Stink\' on it. Somethin\' ain\'t right.',
'As you step away from the strong articulation of the teachings, you get into the pastoral practice of what do you do in some of these very difficult and challenging situations. Sometimes we don\'t come to the same conclusion about how to handle it.',
'The Frankenstein of Communism is the product of the Jewish mind, and was turned loose upon the world by the son of a Rabbi, Karl Marx, in the hopes of destroying Christian civilization',
'Just like Love is yonder rose.',
'Fore warned, fore armed.',
'Other dogs bite only their enemies, whereas I bite also my friends in order to save them.',
'There played around her mouth, and beamed from her eyes, a radiant and tender smile, that seemed gushing from the very heart of womanhood.',
'I imagine that each one of you come from a family, therefore, you should respect it, support it and strengthen it. Especially in a country that has its dynamism founded on it.',
'Without me, you\'ll never be free.',
'Mati harimau meninggalkan belang, mati gajah meninggalkan gading.',
'Ada air ada ikan.',
'Als de kat van huis is, dansen de muizen op tafel.',
'Jika si kucing keluar rumah, tikus-tikus pada menari-nari semuanya di atas meja.',
'Kalau sekarang ini ada yang menjelekkan nama Islam, kita didik agar membawa nama Islam yang damai.',
'Memikul di atas bahu.',
'Anak harimau tidak akan jadi anak kambing.',
'Seperti anai-anai bubus.',
'Jk bbrpa plihn mmbingungkanmu, sdg kau tak tahu mna yg mngundang kridhaan Rabbmu, mka ambillah yg pling mnyelisihi hawa nafsumu.',
'Kebudayaan adalah cermin kebangsaan.',
'Tidak ada lagi waktu luang untuk musik atau bermain biola. Ide Islam kontemporer mulai bernyanyi di telinga saya seperti sebuah melodi, tetapi melodi musik itu kosong tanpa makna intelektual.',
'Tak pandai menari dikatakan lantai yang terjungkat.',
'Bukan biji tak mau tumbuh, tapi bumi tak mau terima.',
'Bagai katak dalam tempurung.',
'Sepuluh jung masuk pelabuhan, anjing bercawat ekor jua.',
'Seperti juga cinta, usia tidak bisa disembunyikan.',
'Ilmu pengetahuan tanpa agama, pincang. Agama tanpa ilmu pengetahuan, buta.',
'Universalisme adalah mitos ketiga.',
'Dalam gedung membuat gedung.',
'Ada nyawa, nyawa ikan.',
'Wahai anakku, jika seseorang menipumu, lalu engkau pura - pura tertipu olehnya, maka engkau telah menipunya.',
'Hij springt van de bok op Jasper.',
'Lindung kucing duduk.',
'Barang tergenggam jatuh terlepas.',
'Lebih mudah mencintai seluruh umat manusia daripada mencintai seorang tetangga.',
'Emping terserak, hari hujan.',
'Maybe there are people who\'ve cut all kinds of corners and they get to the top and they\'re so stoked.',
'Yet the greatest and most fundamental striving is the jihad of the spirit.',
'I think if I had my life again I would not be so utterly self-satisfied.',
'Truth and Virtue do not necessarily belong to wealth and Power and Distinctions of Big Mansions.',
'I have not yet finished my life\'s work.',
'Chaos. Corruption. Civil War.',
'Science vs. Technology',
'Dalam laut bisa diduga, dalam hati siapa tahu.',
'Wan, penghargaan ini tidaklah tepat untuk ibu. Kamulah Nak yang lebih pantas menerimanya. Ibu hanyalah sekadar melahirkanmu Nak.',
'Saya tidak setuju dengan apa yang Anda katakan, tapi akan saya bela mati-matian hak Anda untuk mengatakannya.',
'Orang perlu dihibur untuk menjauhkan mereka dari kekecewaan dalam kehidupan.',
'Sayang-sayang buah kepayang, dimakan mabuk dibuang sayang.',
'Tatkala kita mendengarkam bunyi serangga di rerumputan, orang Jepang menafsirkan bunyi tersebut sebagai bahasa pada belahan kiri dari otak, sementara orang asing menafsirkannya sebagai bunyi pada belahan kanan.',
'Diam diam menghanyutkan.',
'A lot of men and women are knowledgeable about traditional Chinese medicine, including acupuncture, which uses pressure points to deal with a variety of ailments.',
'Kalau prajuritku mulai berpikir, tak seorang pun akan tersisa di pasukanku.',
'Saya bukan saja membela terdakwa, tapi terutama kebenaran dan keadilan.',
'Kau bersembunyi dari kemalangan.',
'Tiada beban dicari beban, pergi ke pulau batu digalas.',
'Seperti kelapa sompong.',
'Een wolf in schaapskleren.',
'Di laut angkatan, di darat kerapatan.',
'Deus vult!',
'Buruk muka cermin dibelah.',
'Bagai aur di atas bukit.',
'Inilah yang harus didorong oleh sistem pendidikan kita. Inilah yang harus mendorong tujuan sosial kita untuk hidup bersama dan bekerja sama, yaitu demi kebaikan bersama. Kebaikan bersama inilah yang harus mempersiapkan kaum muda kita untuk memainkan peran yang dinamis dan konstruktif dalam pengembangan masyarakat di mana semua anggota berbagi secara adil dalam kondisi bersama yang baik maupun yang buruk, di mana kemajuan diukur dalam pengertian kesejahteraan manusia, bukan semata-mata bangunan yang prestisius, mobil, atau hal-hal lain semacam itu, baik milik pribadi maupun milik umum. Oleh karena itu, pendidikan kita harus menanamkan rasa komitmen terhadap komunitas secara total, dan membantu siswa menerima nilai-nilai yang sesuai dengan masa depan kita.',
'Makin murah, makin ditawar.',
'Bagai pungguk merindukan bulan.',
'Jangan pernah mengusik naga yang sedang tidur.',
'True friends stab you in the front.',
'Beranak kandung beranak tiri.',
'Bagai kuku dengan daging.',
'Adat gajah terdorong.',
'Bahasa adalah kemampuan menggunakan tanda ucap atau gerakan oleh manusia untuk mengadakan komunikasi dengan sesamanya.',
'Getah terbangkit kuaran tiba.',
'Apabila sebuah kerajaan semakin korup, maka undang-undangnya semakin banyak.',
'Telah jadi air.',
'Seperti sayur dengan rumput.',
'Daripado jadi ikua gajah, elok jadi kapalo samuik.',
'Daripada jadi seorang bawahan pada suatu perusahaan/instansi/institusi yang besar, lebih baik jadi pimpinan pada usaha sendiri walaupun kecil.',
'Angin tak dapat ditangkap, asap tak dapat digenggam.',
'Rahasia tak selamanya dapat disembunyikan, suatu saat akan terbongkar juga.',
'Ilmu pengetahuan hari ini akan menjadi teknologi pada hari esok.',
'Anda tahu, saya sendiri seorang ilmuwan.',
'Malas itu bukan berarti tidak berbuat apa-apa, tetapi merasa bebas untuk tidak berbuat sesuatu.',
'Kita jangan sampai terlena oleh slogan "bangsa serumpun.",
'Sebagai sebuah negeri Kristen, Belanda berkewajiban meningkatkan kualitas hidup Kristen pribumi di nusantara, memberikan lebih banyak bantuan kepada kegiatan misionaris dan memberikan informasi kepada seluruh administrasi kolonial, bahwa negeri Belanda memiliki kewajiban moral untuk memenuhi kewajiban itu kepada nusantara.',
'Dahulu buah daripada bunga.',
'Merasa sudah memiliki, meskipun sebenarnya belum.',
'Ambil kasih sayang yang tertutup di dada muda kita, simbol tanah tanah Brasil yang tercinta!',
'Ambil kasih sayang yang tertutup di dada muda kita.',
'Satuntuang tabu dek ulek, satuntuang sajo kito buang.',
'Sepotong tebu yang berulat, sepotong saja yang dibuang.',
'Satu dua orang yang berbuat salah, jangan semua keluarga atau kelompoknya yang kita benci.',
'Tidak perlu marah pada semua orang yang ada disekelilingnya.',
'The apple of my eye.',
'Apa yang harus saya pelajari?',
'Aku tidak bisa melihat tanpa meneteskan air mata bahwa landasan kebaikan dan kejahatan terlupakan, atau pada sejumlah kasus benar-benar tak diketahui.',

]