splashList = [
'Jangan takut terhadap orang di posisi manapun, rendah ataupun tinggi, entah dia cendekiawan atau orang yang tidak berpengetahuan. Kalau kau hormat kepada semua manusia, kau harus mengasihi semua orang, dan tidak merasa takut kepada siapapun.',
'Jangan biarkan jati diri menyatu dengan pekerjaan Anda. Jika pekerjaan lenyap, maka jati diri Anda tidak akan pernah hilang.',
'Surga dan Bumi itu abadi. Keduanya abadi karena tidak ada bagi dirinya sendiri. Dengan cara yang sama, orang yang benar-benar suci tak hanya hidup bagi dirinya sendiri, karenanya bisa menjadi abadi dan meraih apapun.',
'Manangguak di aia karuah.',
'Menangguk di air keruh.',
'Mencari keuntungan dalam kekacauan.',
'Tiga hal siapa yang melakukannya, maka ia berpotensi mendapatkan murka: tertawa tanpa ada sesuatu yang mengejutkan, tidur tanpa begadang, dan makan tanpa rasa lapar.',
'Jika Amerika Serikat salah, harapan apa yang kita miliki dari dunia beradab pada gilirannya?',
'Tidak ada yang peduli pada nasib buruh, selama mereka mendapatkan kepuasan secara instan.',
'Had Iraq and Libya been nuclear powers, they wouldn’t have been destroyed in the way we have seen recently. If we had had nuclear capability before 1971, we would not have lost half of our country—present-day Bangladesh—after disgraceful defeat.',
'To project ourselves into their final thoughts will require feelings about a special kind of death - the sudden death in fire of the young, elite, unfulfilled, and seemingly unconquerable. As the elite of young men, they felt more surely than most who are young that they were immortal.',
'HIV/AIDS is a personal challenge, a challenge affecting individuals, families and communities.',
'The Pythagoreans thought those who teach for the sake of reward show themselves worse than sculptors, or artists who perform the work sitting. For these, when someone orders wood to make a statue of Hermes, search for wood suited to receive the proper form; while those pretend that they can readily produce the works of virtue from every nature.',
'Forgive us our trespasses, as we forgive those who trespass against us.',
'Ronnie is the best player in the world at the moment, right-handed, left-handed, one-legged, one-armed, whatever you want!',
'But alas, I\'m going to die!',
'I\'m a chap who...clings to life with the fingernails of both hands.',
'One who drinks of love till it overflows his lips,',
'The other night I sat alone in agony,',
'Listening to the hours pass, wracked with sorrow...',
'I have arrived to face the cold border of nihility.',
'The things which for the most part offer themselves in life, and which, to judge from their actions, men regard as the highest good, can be reduced to these three headings: riches, honour, and sensual pleasure. With these three the mind is so distracted that it is quite incapable of thinking of any other good.',
'AHINDA as a socio-political philosophy can be used as a tool to prevent youths from backward classes and Dalit communities from joining the Hindutva brigade.',
'Wikipedia would have never gotten off the ground without the support of Wales and Bomis.',
'Harvey was not content merely to gather knowledge; he digested and arranged it under the guidance of the faculties which compare and reason.',
'¡Qué rico es ser boricua!',
'Ye monsters of the bubbling deep,<br>Your Maker\'s praises spout;<br>Up from the sands ye codlings peep,<br>And wag your tails about.',
'The silver medal for me was a sign that I would achieve a lot in athletics if I gave it time and work hard.',
'Don\'t know what I\'d do without ya, Ma.',
'So when she wants to take you, she takes you...',
'If controversy means the stimulation of thought and ideas, so much the better.',
'But we, the great, the valiant, and the wise,<br>When once the seal of death has closed our eyes,<br>Lost in the hollow tomb obscure and deep,<br>Slumber, to wake no more, one long unbroken sleep!',
'I\'ll see you next time!',
'When we see a film, half of what we see is what we bring to it.',
'Just because my butt is so humble.',
'A ring around the finger does not cause a nerve block to the genitals.',
'Masuk tak genap, keluar tak ganjil.',
'Makin murah, makin ditawar.',
'Hidung dicium pipi digigit.',
'There must be no hesitation to assume control of the means of production where that is essential in the public interest.',
'Trapped dreams must die.',
'Yew-Kwang Ng is ‘one of the leading economic theorists of his generation’, with a ‘remarkable research record’, who has made ‘major contributions in theoretical Welfare Economics’.',
'O violet-tressed Sappho chaste,<br>O maid with honeyed smile!<br>I fain would tell what is in my breast,<br>Did shame me not beguile.',
'We are the generation that was created by Museveni’s failures...',
'Thank you, Jīya.',
'To the mass of the nation it is the venerability and continuity of our monarchy that gives it so strong and wide a sentimental appeal.',
'It is very important to have the values, the necessary competences to build social cohesion.',
'I believe that a healthy and inclusive democracy is the ultimate check on radicalization.',
'I haven\'t been giving you the silent treatment. I just haven\'t been talking to you.',
'More fool you.',
'Bolshevism destroys not only private property but also private initiative and the readiness to shoulder responsibility. It has not been able to save millions of human beings from starvation in Russia, the greatest Agrarian State in the world.',
'Do you smell something burning?',
'I\'m waiting for valentines.',
'I was attracted to money. I was attracted to the idea of doing what I wanted to do, which was not being a little Southern girl like little Southern girls were for the last, you know, 300 years, but to instead see what it was like to go all over the world and what it was like to be with different people in different places and to see what their lives were like...',
'Let\'s get this party started!',
'Forth, no Soldiers can be quartered in the House of any Freeman in time of Peace, without his will...',
'Did he have passion?',
'By convention sweet is sweet, bitter is bitter, hot is hot, cold is cold, color is color; but in truth there are only atoms and the void.',
'If global warming extinguishes humanity, according to total utilitarianism, that would be an inconceivably bad disaster.',
'Hakimi sebuah pohon dari buahnya, bukan daunnya.',
'Adat bersendi syarak, syarak bersendi adat.',
'Sedekah adalah memberi sesuatu untuk memenuhi kebutuhan orang lain secara sukarela tanpa kepentingan apapun.',
'Emping terserak, hari hujan.',
'Salah satu beban dari pendidikan ekologi adalah kita hidup di dunia yang penuh dengan luka.',
'Gereja bilang bumi itu datar, tapi saya tahu bumi sebenarnya bulat, karena saya telah melihat bayangan bumi yang jatuh di permukaan bulan, dan saya lebih mempercayai bayangan daripada gereja.',
'Air orang disauk, ranting orang dipatah, adat orang diturut.',
'Mencencang memampas, membunuh membangun.',
'Tapi saya sudah nggak peduli dan EGP kalau dia masih tidak mau mengakuinya.',
'Menangguk di air keruh.',
'Alamat biduk akan karam.',
'Dahulu buah daripada bunga.',
'Men kan nooit weten, hoe een koe een haas vangt.',
'Sebagai abu di atas tanggul.',
'Sayangkan kain, buangkan baju.',
'Tak ada yang terbang terlalu tinggi, jika ia terbang menggunakan sayapnya sendiri.',
'Cut your coat according to your cloth.',
'Orang yang sukses adalah mereka yang memiliki sikap optimis sebesar daya kekuatan kuda dan sikap pesimis sebesar rem darurat.',
'Tidak ada seorang pun yang berbuat zina kecuali Allah cabut cahaya iman dari dirinya.',
'Huli man daw at magaling, naihahabol din.',
'Jangan lupa memberi makan burung merpati.',
'Ambillah pakaian orang yang menanggung orang lain, dan tahanlah dia sebagai sandera ganti orang asing',
'Sambil menyelam minum air.',
'Tidak Presiden, tidak saya, dan tidak menteri-menteri dalam akan mengizinkan senjata untuk digunakan melawan rakyat kami.',
'Baguru kapalang aja bagai bungo kambang tak jadi.',
'Lidah bercabang bagai biawak.',
'Yang hampa biar terbang, yang bernas biar tinggal.',
'Sirih pulang ke gagang, pinang pulang ke tampuk.',
'Jika anda bertanya pada saya untuk menamai tiga masalah paling mengerikan yang dihadapi manusia, aku akan memberi jawaban yang sama dengan yang akan dijawab orang lain: perang nuklir, pemanasan global, dan Windows.',
'Na Driekoningen wordt elke dag de stap van de haan langer.',

]