splashList = [
'Jangan takut terhadap orang di posisi manapun, rendah ataupun tinggi, entah dia cendekiawan atau orang yang tidak berpengetahuan. Kalau kau hormat kepada semua manusia, kau harus mengasihi semua orang, dan tidak merasa takut kepada siapapun.',
'Jangan biarkan jati diri menyatu dengan pekerjaan Anda. Jika pekerjaan lenyap, maka jati diri Anda tidak akan pernah hilang.',
'Surga dan Bumi itu abadi. Keduanya abadi karena tidak ada bagi dirinya sendiri. Dengan cara yang sama, orang yang benar-benar suci tak hanya hidup bagi dirinya sendiri, karenanya bisa menjadi abadi dan meraih apapun.',
'Manangguak di aia karuah.',
'Menangguk di air keruh.',
'Mencari keuntungan dalam kekacauan.',
'Tiga hal siapa yang melakukannya, maka ia berpotensi mendapatkan murka: tertawa tanpa ada sesuatu yang mengejutkan, tidur tanpa begadang, dan makan tanpa rasa lapar.',
'Jika Amerika Serikat salah, harapan apa yang kita miliki dari dunia beradab pada gilirannya?',
'Tidak ada yang peduli pada nasib buruh, selama mereka mendapatkan kepuasan secara instan.',
'Had Iraq and Libya been nuclear powers, they wouldn’t have been destroyed in the way we have seen recently. If we had had nuclear capability before 1971, we would not have lost half of our country—present-day Bangladesh—after disgraceful defeat.',
'To project ourselves into their final thoughts will require feelings about a special kind of death - the sudden death in fire of the young, elite, unfulfilled, and seemingly unconquerable. As the elite of young men, they felt more surely than most who are young that they were immortal.',
'HIV/AIDS is a personal challenge, a challenge affecting individuals, families and communities.',
'The Pythagoreans thought those who teach for the sake of reward show themselves worse than sculptors, or artists who perform the work sitting. For these, when someone orders wood to make a statue of Hermes, search for wood suited to receive the proper form; while those pretend that they can readily produce the works of virtue from every nature.',
'Forgive us our trespasses, as we forgive those who trespass against us.',
'Ronnie is the best player in the world at the moment, right-handed, left-handed, one-legged, one-armed, whatever you want!',
'But alas, I\'m going to die!',
'I\'m a chap who...clings to life with the fingernails of both hands.',
'One who drinks of love till it overflows his lips,',
'The other night I sat alone in agony,',
'Listening to the hours pass, wracked with sorrow...',
'I have arrived to face the cold border of nihility.',
'The things which for the most part offer themselves in life, and which, to judge from their actions, men regard as the highest good, can be reduced to these three headings: riches, honour, and sensual pleasure. With these three the mind is so distracted that it is quite incapable of thinking of any other good.',
'AHINDA as a socio-political philosophy can be used as a tool to prevent youths from backward classes and Dalit communities from joining the Hindutva brigade.',
'Wikipedia would have never gotten off the ground without the support of Wales and Bomis.',
'Harvey was not content merely to gather knowledge; he digested and arranged it under the guidance of the faculties which compare and reason.',
'¡Qué rico es ser boricua!',
'Ye monsters of the bubbling deep,<br>Your Maker\'s praises spout;<br>Up from the sands ye codlings peep,<br>And wag your tails about.',
'The silver medal for me was a sign that I would achieve a lot in athletics if I gave it time and work hard.',
'Don\'t know what I\'d do without ya, Ma.',
'So when she wants to take you, she takes you...',
'If controversy means the stimulation of thought and ideas, so much the better.',
'But we, the great, the valiant, and the wise,<br>When once the seal of death has closed our eyes,<br>Lost in the hollow tomb obscure and deep,<br>Slumber, to wake no more, one long unbroken sleep!',
'I\'ll see you next time!',
'When we see a film, half of what we see is what we bring to it.',
'Just because my butt is so humble.',
'A ring around the finger does not cause a nerve block to the genitals.',
'Masuk tak genap, keluar tak ganjil.',
'Makin murah, makin ditawar.',
'Hidung dicium pipi digigit.',
]