splashList = [
'Jangan pakai retinol di wajah yang basah',
'Pastikan wajah sudah benar-benar kering saat memakai retinol',
'Retinol di wajah yang basah dapat mengakibatkan iritasi',
'Jangan terburu-buru menaikkan frekuensi penggunaan retinol',
'Jangan mulai penggunaan retinol dengan dosis tinggi, mulailah dari dosis 0,5% untuk pemula',
'Jangan campurkan retinol yang akan digunakan di wajah dengan vitamin C',
'Jangan campurkan retinol yang akan digunakan di wajah dengan AHA',
'Jangan campurkan retinol yang akan digunakan di wajah dengan BHA',
'Kuina fell down the steps at home and died...',
'Kekeke',
'Enjoy!',
'\\(Ax^{2} + Bx + C = 0\\) has one and only one solution if and only if \\(\\Delta = B^{2}-4AC = 0\\).',
'We respected the four fallen',
'We blessed the statue',
'We gazed upon the fountain',
'We lit candles for our tributes',
'The sphere, representing Creativity. It is what keeps us alive.',
'Welcome to OtherWorld!',
'Enjoy your time here :)',
'All of creation is at your fingertips. What will you dream up?',
'The cube, representing Community. It is what connect us.',
'The pyramid representing Structure. It is what holds us together.',
'oh... hello.. friend',
'Dance the nightt away!',
'The clock is ticking!',
'.ria eht ni cisum syawla s\'erehT',
'(:',
'*knock*',
'Although we lost our friends in the outer worlds, they will never be forgotten in our virtual world.',
'Look at how the stars shine.',
'Look at how the stars shine. See how they twinkle and blink.',
'Bits and bytes are just 1\'s and 0\'s, two states of being, on and off, soft and loud, short and long. But in those two states, they hold eternity.',
'Opportunity is a knock at the door. Sometimes it\'s several knocks.',
]