splashList = [
'Grow your business online today!!',
'Web Portals are different from normal website in their usage. They primarily focus on online community building and get users to register and use the services on regular basis.',
'A web portal is a highly beneficial access point to the web for individual as well as business users.',
'The information contained in a web content portal is categorized into links to topics such as news, business, finance, travel, sports and more.',
'Initially used by the general public for purposes such as email, public forums, search engines, online shopping and more, web portals today provide a multitude of other functions.',
'Seeking for business development get associated with online portals!',
'Give your business a massive head-start',
'Change is the only constant in life.',
'With the advent of internet, the whole experience of shopping has transformed from visiting a real store to shop to making online purchases with ease and comfort.',
'Ecommerce is the latest mantra for the businesses in this era of technology.',
'Small to big, simple to complex, all kinds of businesses are leveraging the benefits of internet via ecommerce to make better sales and earn better profits.',
'Ecommerce development no doubt plays a very important role in managing business across the globe.',
'Need help?',
'Need help? Speak to us <a target="_blank" class="generated-text" href="https://web.facebook.com/groups/363720887799746">here</a>!',
'Need help? Speak to us <a target="_blank" class="generated-text" href="https://t.me/+qH41VDjHzzsyZThl">here</a>!',
'Need help? Speak to us <a target="_blank" class="generated-text" href="https://discord.com/invite/4MM7WY2xku">here</a>!',
'Enrich your business in minutes',
'With the growing trends of globalization, each and every business firm is willing to expand its reach.',
'Business Portals offers more than 100 Business to Business portals, for each business a separated portal.',
'A further business-driven requirement of portals is that the content be able to work on multiple platforms.',
'Your Way to Property and Prosperity',
'Real estate is in its peaks of development.',
'Real estate is growing in leaps and bounds, wizzering off all possible barriers in its way.',
'Join hands to decide your Life',
'One of the fastest growing industry on the internet in India is online matrimonial portals.',
'Online matrimonial portals provide a platform to the aspiring brides/grooms to search for their life partner by automating calculations, comparisons in a massive profile database.',
'Where expertise meet excellence.',
'In today\'s era lots of students graduate every year and begin their search for jobs.',
'Job portal is what serve as the solution for online job search.',
'Knowing the presence of the world',
'News portal is one of the ways to reach the current information and technology news and market trends.',
'Nowadays people use online news portal or website to know the latest updates and news across the globe.',
'It is flexible to read and get the latest news everywhere that you want via online news portal.',
'中国证券报社版权所有，未经书面授权不得复制或建立镜像',
'But it doesn’t have to be…',
'Sezzle can only be used for US and Canada purchases.',
'A tax that pulverized digital-asset trading in India has proved counterproductive and ought to be lowered, according to CoinDCX, a domestic exchange that was valued at over $2 billion before the levy was imposed.',

]