splashList = [
'Perjuangan bangsa Indonesia sebelum abad ke-20 bersifat lokal atau kedaerahan.',
'Perjuangan bangsa Indonesia sebelum abad ke-20 dilakukan secara fisik dengan senjata tradisional.',
'Perjuangan bangsa Indonesia sebelum abad ke-20 dipimpin tokoh yang karismatik.',
'Perjuangan bangsa Indonesia sebelum abad ke-20 bersifat sporadis.',
'Bipatride merupakan kondisi saat seorang penduduk mempunyai dua macam kewarganegaraan sekaligus atau dikenal sebagai kewarganegaraan ganda.',
'Bipatride dapat terjadi saat seorang anak keturunan bangsa B yang menganut asas <i>ius sanguinis</i> lahir di negara A yang menganut asas <i>ius soli</i>.',
'Dokuritsu Junbi Cosakai atau BPUPKI didirikan oleh Kumaikici Harada pada tanggal 1 Maret 1945 dengan maksud agar Indonesia membantu Jepang melawan sekutu.',
'Sistem pertahanan dan keamanan Indonesia menurut UUD 1945 adalah upaya pertahanan dan keamanan negara yang dilaksanakan melalui sistem pertahanan dan keamanan rakyat semesta.',
'Anata wa o hana wo suki desuka?',
'Watashi wa ima jouzu desu yo!',
'Watashi wa ima mou wakarimasu.',
'Ima wa sukoshi dake da yo.',
'Amari mucha suruna yo!',
'Shiawase ni wa takusan aru yo.',
'Watashi wa zenzen kizukenakatta.',
'Doushite naite ita no desuka?',
'Ima kara hajimemashou ka?',
'Apa kamu sudah selesai belajar?',
'Rumus mencari sekala. Jarak pada gambar dibagi jarak sebenarnya.',
'Sholat yang dapat dijamak: zuhur dengan asar, maghrib dengan isya.',
'OJK (Otoritas Jasa Keuangan) adalah lembaga yang difungsikan pemerintah untuk melakukan pengendalian dan pengecekan kegiatan perbankan.',
'Persatuan dan kesatuan adalah alat untuk membantu mencapai tujuan bangsa.',
'Salah satu tujuan bangsa Indonesia adalah melindungi segenap bangsa Indonesia dan seluruh tumpah darah Indonesia.',
'Salah satu tujuan bangsa Indonesia adalah memajukan kemaslahatan umum.',
'Salah satu tujuan bangsa Indonesia adalah mencerdaskan kehidupan bangsa.',
'Salah satu tujuan bangsa Indonesia adalah mewujudkan ketertiban dunia yang berdasarkan kemerdekaan, perdamaian abadi, dan keadilan sosial.',
'Persatuan dan kesatuan mengatasi perbedaan dan menghilangkan diskriminasi.',
'Persatuan dan keutuhan bangsa dapat mengatasi perbedaan bangsa Indonesia yang terdiri dari berbagai suku dan budaya.',
'Rasa persatuan dan kesatuan akan menghilangkan diskriminasi karena semua orang adalah satu Indonesia.',
'Persatuan dan kesatuan untuk terpeliharanya keutuhan NKRI.',
'Persatuan dan kesatuan memelihara perdamaian negara kesatuan Republik Indonesia.',
'Persatuan dan kesatuan memperkuat ketahanan nasional dalam mempertahankan NKRI dari ancaman eksternal.',
'Persatuan dan kesatuan memperkuat jati diri bangsa Indonesia, mencegah terjadinya perang atau konflik antar suku dan antar daerah di Indonesia.',
'Persatuan dan kesatuan ciptakan kerukunan antar warga.',
'Persatuan dan kesatuan membangun bangsa Indonesia yang lebih maju dan aman, menciptakan rasa toleransi dan toleransi dalam menghadapi perbedaan.',
'Kita ciptakan rasa kekeluargaan, semangat kebersamaan, gotong royong, peduli sesama dan gotong royong dalam kehidupan bermasyarakat.',
'Persatuan dan kesatuan mewujudkan masyarakat yang lebih baik, lebih rukun, lebih seimbang, lebih rukun, lebih damai, lebih setia, aman dan damai.',
'Ketika manusia jatuh dalam dosa maka hati nuraninya sudah​ kotor',
'Youtube adalah contoh media sosialisasi digital.',
'Indonesia terletak di antara dua benua yaitu benua Asia dan benua Australia.',
'Tanpa adanya pancasila, negara indonesia tidak akan berdiri kokoh atau tidak memiliki dasar yang kuat',

]